pipeline {
    agent any
    environment {
        IMAGE_NAME = 'shivam/stock-tracker'  // Change this to your DockerHub repo name
        DOCKER_CREDENTIALS_ID = 'DOCKER_CRED'  // Jenkins credentials ID for DockerHub
        SONAR_CREDENTIALS_ID = 'SONAR_TOKEN'  // SonarQube credentials ID
    }
    stages {
        stage('Build') {
            steps {
                dir('stock-tracker') {
                    script {
                        echo 'Building the project...'
                        bat 'mvn clean install'
                    }
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn sonar:sonar -Dsonar.projectKey=stock-tracker -Dsonar.host.url=http://localhost:9000 -Dsonar.login=%SONAR_CREDENTIALS_ID%'
                    }
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    withDockerRegistry([credentialsId: DOCKER_CREDENTIALS_ID, url: '']) {
                        dir('stock-tracker') {
                            echo 'Building Docker image...'
                            bat "docker build -t ${IMAGE_NAME}:latest ."

                            echo 'Pushing Docker image to registry...'
                            bat "docker push ${IMAGE_NAME}:latest"
                        }
                    }
                }
            }
        }
        stage('Nexus Deploy') {
            steps {
                dir('stock-tracker') {
                    script {
                        echo 'Deploying to Nexus...'
                        def mavenPom = readMavenPom file: 'pom.xml'
                        nexusArtifactUploader(
                            nexusVersion: 'nexus3',
                            protocol: 'http',
                            nexusUrl: 'localhost:8090',
                            groupId: "${mavenPom.groupId}",
                            version: "${mavenPom.version}",
                            repository: 'INTEGRATIONS_CLIENT',
                            credentialsId: 'NEXUS_CRED',
                            artifacts: [
                                [artifactId: "${mavenPom.artifactId}",
                                 classifier: '',
                                 file: "./target/${mavenPom.artifactId}-${mavenPom.version}.war",
                                 type: 'jar'],
                                [artifactId: "${mavenPom.artifactId}",
                                 classifier: '',
                                 file: "pom.xml",
                                 type: "pom"]
                            ]
                        )
                    }
                }
            }
        }
        stage('JBoss Deployment') {
            steps {
                dir('integration_clients') {
                    withCredentials([usernamePassword(credentialsId: 'JBOSS_CRED', usernameVariable: 'JBOSS_CRED_USER', passwordVariable: 'JBOSS_CRED_PASSWORD')]) {
                        script {
                            echo 'Deploying to JBoss....'
                            def mavenRepoLocal = 'C:\\Users\\shivam.upadhyay\\.m2\\repository'
                            bat """
                                mvn -Dmaven.repo.local=${mavenRepoLocal} wildfly:deploy-only -Dwildfly.username=%JBOSS_CRED_USER% -Dwildfly.password=%JBOSS_CRED_PASSWORD%
                            """
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build and Deployment succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
