pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('stock-tracker') {
                    script {
                        echo 'Building the project...'
                        bat 'mvn clean install'
                    }
                }
            }
        }
        stage('Nexus Deploy') {
            steps {
				dir('stock-tracker') {
					script{
						echo 'Deploying....'
						def mavenPom = readMavenPom file: 'pom.xml'
						nexusArtifactUploader(
							nexusVersion: 'nexus3',
							protocol: 'http',
							nexusUrl: 'localhost:8090',
							groupId: "${mavenPom.groupId}",
							version: "${mavenPom.version}",
							repository: 'INTEGRATIONS_CLIENT',
							credentialsId: 'NEXUS_CRED',
							artifacts: [
								[artifactId: "${mavenPom.artifactId}",
								 classifier: '',
								 file: "./target/${mavenPom.artifactId}-${mavenPom.version}.war",
								 type: 'jar'],
								 [artifactId: "${mavenPom.artifactId}",
								  classifier: '',
								  file: "pom.xml",
								  type: "pom"]
							]
						 )
					 }
				}
            }
        }
	stage('JBoss Deployment') {
	    steps {
	        dir('integration_clients') {
	            withCredentials([usernamePassword(credentialsId: 'JBOSS_CRED', usernameVariable: 'JBOSS_CRED_USER', passwordVariable: 'JBOSS_CRED_PASSWORD')]) {
	                script {
	                    echo 'Deploying to JBoss....'
	
	                    // Define the local Maven repository path
	                    def mavenRepoLocal = 'C:\\Users\\shivam.upadhyay\\.m2\\repository'
	
	                    // Deploy to JBoss using Maven on Windows
	                    bat """
	                        mvn -Dmaven.repo.local=${mavenRepoLocal} wildfly:deploy-only -Dwildfly.username=%JBOSS_CRED_USER% -Dwildfly.password=%JBOSS_CRED_PASSWORD%
	                    """
	                }
	            }
	        }
	    }
	}
    }
    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
